### ISSUE TITLE
Various sdl packages: why not official?

### ISSUE THREAD

**Issue by deralmas** [sdsddsd1/kiss-games#30]
I see that there are some sdl* family packages:
- sdl-image
- sdl-mixer
- sdl-ttf
- sdl2-image
- sdl2-mixer
- sdl2-ttf

The main libraries have official packages, why not merging these into community and making them official too?

**Comment by sdsddsd1** [comment]
There is `sdl` and `sdl2` in community because other packages depend on them. There is no need for a library to be in community without something depending on it.
When some of those or other libraries of this repo are added to community I have to manual remove them or the user has to on their own discretion. I have not figured out a better system for this.
I think dylan is also against adding "useless" libraries to community and I think thats right because there should only be whats necessary.

**Comment by deralmas** [comment]
Wouldn't it be better to create another repo just for these and other dependencies? For example, there could be a sdl-libs repo that could have these. It feels kinda weird having some development libraries in a games repo, but i might not be seeing the full picture.

**Comment by sdsddsd1** [comment]
I see a point but this would overcomplicate the whole. Imagine to add several kiss-games repos. Also look at `community` there is everything in one place. It might me chaotic but saves work to maintain and everything is always at the right spot.
I would kindly refer to the [Readme](https://github.com/sdsddsd1/kiss-games/blob/master/README.md)  ;)

**Comment by deralmas** [comment]
I see, makes sense :). Closing the issue as it's resolved then. Thanks for the info!
