### ISSUE TITLE
Scons: why not a package?

### ISSUE THREAD

**Issue by deralmas** [sdsddsd1/kiss-games#31]
Some packages, require scons in order to be built. Godot in order to compile always runs [`pip install scons`](https://github.com/sdsddsd1/kiss-games/blob/4843c92e983574eeb9996ea3bde8c51d42342984/godot/build#L3) which seems pretty bad imo. In this repository there are some development package, why not then adding it to the repository?

**Comment by sdsddsd1** [comment]
Yeah you are absolutely right. But I have no better idea how to solve this.
I didnt want to add a python pkg. But maybe it should.
Pullrequests welcome!
Edit: 
Look at this mess of dependecies: [Scons Pkgbuild](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/scons)

**Comment by deralmas** [comment]
>  Look at this mess of dependecies: Scons Pkgbuild

I don't understand, would you still add a scons package?

**Comment by sdsddsd1** [comment]
I dont want to add scons as a package because its awful to package and would pull rattail of deps with it.
Maybe we can adopt the build of [firefox](https://github.com/kisslinux/repo/blob/master/extra/firefox/build#L17)

**Comment by deralmas** [comment]
Wait i'm not understanding again, the link points to the building of autoconf, are you referring to the way that it's built?

**Comment by deralmas** [comment]
If I understand correctly, you would like to build all of its dependencies in the scons build file, right?
If that's the case, that seems like a really good idea, since a lot its dependencies are software that will probably never be used outside of building scons.

**Comment by sdsddsd1** [comment]
I want to install `scons` through `pip` in a PATH of the package itself.
Installing `scons` dependencies in a PATH of the package would not solve the issue of bringing a myriad of dependencies into packaging.
`pip install --install-option="--prefix=$PREFIX_PATH" package_name` should do the trick but I have no success so far.
Anyway, because installing through pip is a `working`  solution, I would levae a note in post-install and encourage the user to `kiss-fork` and adjust the package to their own discretion

**Comment by sdsddsd1** [comment]
[See](https://github.com/sdsddsd1/kiss-games/issues/33).
Thanks for putting light on this.
